#base on meta-raspberrypi 4 BSP
require conf/machine/raspberrypi4-64.conf

MACHINE ??= "raspberrypi4-64"

# custom settings
ENABLE_UART = "1"
RPI_USE_U_BOOT = "1"

# (optional) extra settings
# KERNEL_IMAGETYPE = "uImage"
