pipeline {
    agent any

    options {
       timestamps()
       timeout(time: 8, unit: 'HOURS') // Increased timeout to 2 hours
    }

    environment {
        PRJ = "${env.WORKSPACE}"
        DOCKER_IMAGE = 'yocto_img:latest'
        DOCKER_CONTAINER_NAME = 'yocto_container'
    }

    stages {
        stage('Pull Docker Image') {
            steps {
                script {
                    // Check if the Docker image exists locally
                    def imageExists = sh(script: "docker images -q ${env.DOCKER_IMAGE}", returnStdout: true).trim()
                    if (imageExists == "") {
                        echo "Docker image ${env.DOCKER_IMAGE} not found locally. Pulling from Docker Hub..."
                        retry(2) { //try max 2x 
                            sh(script: "docker pull ${env.DOCKER_IMAGE}", returnStdout: true, returnStatus: false).eachLine { line ->
                                echo line
                            }
                        }
                        echo "Docker image ${env.DOCKER_IMAGE} successfully pulled."
                    } else {
                        echo "Docker image ${env.DOCKER_IMAGE} already exists locally. Skipping pull."
                    }

                    //Verify Docker Image
                    def imageVerify = sh(script: "docker images -q ${env.DOCKER_IMAGE}", returnStdout: true).trim()
                    if (imageVerify == "") {
                        error "Docker image ${env.DOCKER_IMAGE} not found after pull. Aborting."
                    } else {
                        echo "Docker image ${env.DOCKER_IMAGE} is available locally."
                    }

                    //Verify Docker container. If active, treat is as it was zombie
                    def containerVerify = sh(script: "docker ps -a --filter 'name=${DOCKER_CONTAINER_NAME}' --format '{{.Names}}'", returnStdout: true).trim()
                    if (containerVerify != "") {
                        sh'''
                            docker stop ${DOCKER_CONTAINER_NAME}
                            docker rm ${DOCKER_CONTAINER_NAME}
                        '''
                    } 
                }
            }
        }

        stage('build yocto image') {
            steps{
                script {
                    //Docker seems to have problem with building inside volume mapped folder. It crash PC unexpectedly
                    //That is why we are using /home/pokyuser/localWorkdir inside container instead of /volume/localWorkdir.
                    //'volume' is mapped to /home/media/jenkins_home on host. We only use /volume to copy artefacts back to host.
                    sh '''
                        docker run --rm --name ${DOCKER_CONTAINER_NAME} \
                        -v /home/media/jenkins_home:/volume:rw \
                        -w /volume \
                        --user pokyuser \
                        ${DOCKER_IMAGE} /bin/bash -c "

                        echo '----------- Clean (artefacts) YoctoRpi folder on host-----------'
                        rm -rf /volume/YoctoRpi/*

                        echo '----------- Build yocto image start -----------'
                        mkdir -p /home/pokyuser/localWorkdir
                        cd /home/pokyuser/localWorkdir
                        repo init -u https://github.com/zhalat/manifests.git -b rpi4/scarthgap -m default.xml
                        repo sync -j$(nproc) 
                        MACHINE=zh-rpi4 DISTRO=zh-distro source ./demo-custom-setup.sh build
                        bitbake zh-image
                        echo '----------- Build yocto image finished -----------'

                        echo '----------- Copy build artefacts to host -----------'
                        # Dereference any symlinks and overwrite existing targets with the real files
                        cp -L --remove-destination /home/pokyuser/localWorkdir/build/tmp/deploy/images/zh-rpi4/zh-image-zh-rpi4.rootfs.wic.bz2 /volume/YoctoRpi/
                        cp -L --remove-destination /home/pokyuser/localWorkdir/build/tmp/deploy/images/zh-rpi4/zh-image-zh-rpi4.rootfs.tar.bz2 /volume/YoctoRpi/
                        cp -L --remove-destination /home/pokyuser/localWorkdir/build/tmp/deploy/images/zh-rpi4/zh-image-zh-rpi4.rootfs.manifest /volume/YoctoRpi/
                        cp -L --remove-destination /home/pokyuser/localWorkdir/build/tmp/deploy/images/zh-rpi4/zh-image.env /volume/YoctoRpi/
                        cp -L --remove-destination /home/pokyuser/localWorkdir/build/tmp/deploy/images/zh-rpi4/Image /volume/YoctoRpi/
                        cp -L --remove-destination /home/pokyuser/localWorkdir/build/tmp/deploy/images/zh-rpi4/boot.scr /volume/YoctoRpi/
                        "
                    '''
                }
                
                //Archive  the image file
                script {
                    def imgDir = "/var/jenkins_home/YoctoRpi"
                    sh """
                        if [ -d "${imgDir}" ]; then
                            zip -r ${env.WORKSPACE}/Rpi4SdImage.zip "${imgDir}"
                        else
                            exit 1
                        fi
                    """
                    archiveArtifacts artifacts: "Rpi4SdImage.zip", allowEmptyArchive: false
                }
            }
        }
    }
}
 